### ISSUE TITLE
An issue about d_beh repo

### ISSUE THREAD

**Issue by Zizhuang-Miao** [spatialtopology/spacetop-prep#55]
### Which module is this from?
 `d_beh` repo
(Write your answer here: beh, datalad, fmriprep, mriqc, physio, qcplot, redcap)

### What is the issue?
 The naming or folder structure for the beh files of task-faces of four subjects is different from others. The four subjects are: sub-0003, sub-0004, sub-0005, sub-0008
(Write your answer here.)

### What was your expected behavior?
 Change all beh file names to start with f"{sub}_{session}_{task}_{run}-{rating_type}". For sub-0008, merge the task-AGE, task-SEX, and task-INTENSITY folder into one task-faces folder.
(Write your answer here.)

### How can we reproduce this?

(Write your answer here.)

### Any additional context?

(Write your answer here.)

**Comment by jungheejung** [comment]
@Zizhuang-Miao thanks for finding this! Could you take a stab at this?

**Comment by jungheejung** [comment]
Awesome, will close!
