### ISSUE TITLE
[BUG] spurious sub-0019/ses-19 generated by ./code/spacetop-prep/spacetop_prep/events/bidsify_fractional.py

### ISSUE THREAD

**Issue by yarikoptic** [spatialtopology/spacetop-prep#75]
introduced in 8fa5bbbf71f427997cd0e1ad0cc9fe21d2a7e647

**Comment by jungheejung** [comment]
@bogpetre Bogdan, you resolved this, correct?

**Comment by jungheejung** [comment]
Resolved issue via commit d6e4c7893612c4a09febf367048e6510666692e4 in spacetop rolando-exchange
