### ISSUE TITLE
[BUG] _events durations might still be empty instead of a number of n/a

### ISSUE THREAD

**Issue by yarikoptic** [spatialtopology/spacetop-prep#78]
some produced `_events.tsv` files have empty cells for `duration` whenever according to bids
https://bids-specification.readthedocs.io/en/stable/modality-specific-files/task-events.html it should be either number of `n/a`:

![image](https://github.com/spatialtopology/spacetop-prep/assets/39889/6de100f4-9a84-42e1-9588-8b9a05deb860)

I think it would be better if script which produces those files was adjusted and reran instead of me fixing them up.

examples: see e.g `sub-0001/ses-04/func/sub-0001_ses-04_task-fractional_acq-mb8_run-02_desc-tomspunt_events.tsv` for onset 24.43936014175415

WDYT?

**Comment by jungheejung** [comment]
Resolved via commit 992fa40
